# -*- coding: utf-8 -*-
"""spacy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VTd598_qMNMSXfIc7Vim7y6k5XkvB4wJ
"""



import spacy
nlp=spacy.load('en_core_web_sm')

doc=nlp(u'India is helding the cricket world cup this year')

for token in doc.ents:
  print(token,token.label_)