# -*- coding: utf-8 -*-
"""Import _files_from_drive_to_colab.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dnGINiAH0UNfc4GE2a5nyjzkIGzdFY3L
"""

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth =GoogleAuth()
gauth.credentials=GoogleCredentials.get_application_default()
drive=GoogleDrive(gauth)

downloaded=drive.CreateFile({'id':'1ouv2WQZT7CD-Zf0m3oYISQBjhxUd1aKt'})
downloaded.GetContentFile('owlcreek.txt')



